### PR TITLE
#52 Investigate the updater's git resource use

### LINKED ISSUE #52: Investigate the updater's git resource use
- [x] Nightly updater's `git push` command runs without failing due to resource limits

## Details

When the updater has committed large metadata changes it fails on `git push`.

Error:

```bash
# git push
Enumerating objects: 11754, done.
Counting objects: 100% (10881/10881), done.
error: pack-objects died of signal 9
error: pack-objects died of signal 9
error: remote unpack failed: eof before pack header was fully read
```

### PR DESCRIPTION
**Pull request by sighmon**
Resolves #52

When trying to `git push` large changes of the ~45,000 JSON files, git runs out of memory.

Let's attempt to solve this by using this method: https://stackoverflow.com/a/36189893

### Acceptance Criteria
- [x] Nightly updater's `git push` command runs without failing due to resource limits

### Relevant design files
* None

### Testing instructions
1. Bash into a pod after the updater fails and run `git fetch --unshallow`
1. Note that you can now successfully `git push` that night's commit

### DoD
For requester to complete:
- [x] All acceptance criteria are met
~- [ ] New logic has been documented~
~- [ ] New logic has appropriate unit tests~
- [ ] Changelog has been updated if necessary
~- [ ] Deployment / migration instruction have been updated if required~

### CODE REVIEW

**Comment by framigni** [comment]
sorry, I'm struggling to understand the logic here, probably because my scarce knowledge of Git:

1. it runs a `git pull` (so is that a "shallow" fetch ?)
2. it switches to main
3. it runs a `git fetch --unshallow`
4. so where is the advantage for the `git push` then ? why shouldn't it fail ?

**Comment by framigni** [comment]
> 

ok, but still not clear to me why then the git push would not top 100% memory in this case... anyway, if it works...
cool, thanks

**Review by framigni — APPROVED** [review]

**Review by sam-maher-acmi — APPROVED** [review]
Let's give it a shot.

**Comment by sighmon** [comment]
@framigni The primitive way I understand how git works - it's a tradeoff between speed and resource use:

**Full git clone**:
* Big download up front, less CPU/network use during changes
* Any change comparison is optimised as all data is available on the filesystem

**Shallow git clone**:
* Small fast download up front, more CPU/network use during changes
* Only the last commit is available on the filesystem, so any change comparison requires network requests
* Presumably the bigger the repo/number of commits, the more requests - so perhaps this is why our pods resource limits are hit
* Seeing we're doing diffs on up to ~45,000 files, this doesn't scale well

**Pull request merged**
